#配置数据库
spring:
  datasource:
    url: jdbc:mysql://${sql.url}:3306/payroll_management?characterEncoding=UTF-8&&serverTimezone=GMT&&allowMultiQueries=true&&&rewriteBatchedStatements=true&&allowPublicKeyRetrieval=true
    username: ${sql.username}
    password: ${sql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

#  配置请求参数
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 200MB #最大请求文件的大小
      max-file-size: 200MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写

# 配置mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名

sql:
  url: 
  username: 
  password: 
